version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "4000:3306"  # Map host port 4000 to container port 3306
    networks:
      - backend

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "5000:5000"  # Map host port 5000 to container port 5000
    depends_on:
      - mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge
